# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ec73ba95f1ae2f1c13d1df7dd4a93c464c651ac0f2d3d6ff94497ca8dbf371a1d2a8709ad6abcf3e4dc7e66ef4fe7b6f761a2d54779c88845c549161b11dbc

test:
  secret_key_base: 517f6a8b50616dabd0e878040714d9eb8677d29a1055a52b40c1aed4ffb1f756b627b024995478d54a6f5d30c112e73dd6d118a2a5c40167a8d1e25145a181da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
